//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corporacion_Nivel1
    {
        public long IdNivel1 { get; set; }
        public Nullable<long> IdAno { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public Nullable<long> Monto { get; set; }
    
        public virtual Corporacion_Ano Corporacion_Ano { get; set; }
    }
}
