//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastoInformev2
    {
        public long IdGastoInforme { get; set; }
        public string Codigo { get; set; }
        public string Cuenta { get; set; }
        public Nullable<double> MontoPresupuestado { get; set; }
        public Nullable<double> MontoGastado { get; set; }
        public Nullable<System.DateTime> UpdatedOnUTC { get; set; }
        public Nullable<System.Guid> IdGroupInformeGasto { get; set; }
        public Nullable<int> TipoCodigo { get; set; }
        public string TipoNombre { get; set; }
    }
}
