//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GastoTransparenteMunicipalEntities : DbContext
    {
        public GastoTransparenteMunicipalEntities()
            : base("name=GastoTransparenteMunicipalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InformeGasto> InformeGasto { get; set; }
        public virtual DbSet<InformeGastoGeneral> InformeGastoGeneral { get; set; }
        public virtual DbSet<InformeGastoNivel1> InformeGastoNivel1 { get; set; }
        public virtual DbSet<InformeGastoNivel2> InformeGastoNivel2 { get; set; }
        public virtual DbSet<InformeGastoNivel3> InformeGastoNivel3 { get; set; }
        public virtual DbSet<InformeGastoNivel4> InformeGastoNivel4 { get; set; }
        public virtual DbSet<InformeIngreso> InformeIngreso { get; set; }
        public virtual DbSet<InformeIngresoGeneral> InformeIngresoGeneral { get; set; }
        public virtual DbSet<InformeIngresoNivel1> InformeIngresoNivel1 { get; set; }
        public virtual DbSet<InformeIngresoNivel2> InformeIngresoNivel2 { get; set; }
        public virtual DbSet<InformeIngresoNivel3> InformeIngresoNivel3 { get; set; }
        public virtual DbSet<InformeIngresoNivel4> InformeIngresoNivel4 { get; set; }
        public virtual DbSet<InformePersonalAdmServicios> InformePersonalAdmServicios { get; set; }
        public virtual DbSet<InformePersonalCategoriaAdmServicios> InformePersonalCategoriaAdmServicios { get; set; }
        public virtual DbSet<InformePersonalCategoriaCementerio> InformePersonalCategoriaCementerio { get; set; }
        public virtual DbSet<InformePersonalCategoriaEducacion> InformePersonalCategoriaEducacion { get; set; }
        public virtual DbSet<InformePersonalCategoriaMunicipioTotal> InformePersonalCategoriaMunicipioTotal { get; set; }
        public virtual DbSet<InformePersonalCategoriaSalud> InformePersonalCategoriaSalud { get; set; }
        public virtual DbSet<InformePersonalCementerio> InformePersonalCementerio { get; set; }
        public virtual DbSet<InformePersonalEducacion> InformePersonalEducacion { get; set; }
        public virtual DbSet<InformePersonalResultadoAdmServicios> InformePersonalResultadoAdmServicios { get; set; }
        public virtual DbSet<InformePersonalResultadoCementerio> InformePersonalResultadoCementerio { get; set; }
        public virtual DbSet<InformePersonalResultadoEducacion> InformePersonalResultadoEducacion { get; set; }
        public virtual DbSet<InformePersonalResultadoMunicipioTotal> InformePersonalResultadoMunicipioTotal { get; set; }
        public virtual DbSet<InformePersonalResultadoSalud> InformePersonalResultadoSalud { get; set; }
        public virtual DbSet<InformePersonalSalud> InformePersonalSalud { get; set; }
        public virtual DbSet<InformeProveedoresAdmServicios> InformeProveedoresAdmServicios { get; set; }
        public virtual DbSet<InformeProveedoresCementerio> InformeProveedoresCementerio { get; set; }
        public virtual DbSet<InformeProveedoresEducacion> InformeProveedoresEducacion { get; set; }
        public virtual DbSet<InformeProveedoresResumenAdmServicios> InformeProveedoresResumenAdmServicios { get; set; }
        public virtual DbSet<InformeProveedoresResumenCementerio> InformeProveedoresResumenCementerio { get; set; }
        public virtual DbSet<InformeProveedoresResumenEducacion> InformeProveedoresResumenEducacion { get; set; }
        public virtual DbSet<InformeProveedoresResumenMunicipioTotal> InformeProveedoresResumenMunicipioTotal { get; set; }
        public virtual DbSet<InformeProveedoresResumenSalud> InformeProveedoresResumenSalud { get; set; }
        public virtual DbSet<InformeProveedoresSalud> InformeProveedoresSalud { get; set; }
        public virtual DbSet<InformeSubsidio> InformeSubsidio { get; set; }
        public virtual DbSet<InformeSubsidioCategoria> InformeSubsidioCategoria { get; set; }
        public virtual DbSet<InformeSubsidioOrganizacion> InformeSubsidioOrganizacion { get; set; }
        public virtual DbSet<Municipalidad> Municipalidad { get; set; }
        public virtual DbSet<InformeCorporaciones> InformeCorporaciones { get; set; }
    
        public virtual int SP_InformeGasto(Nullable<System.Guid> idGroupReportGasto)
        {
            var idGroupReportGastoParameter = idGroupReportGasto.HasValue ?
                new ObjectParameter("IdGroupReportGasto", idGroupReportGasto) :
                new ObjectParameter("IdGroupReportGasto", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeGasto", idGroupReportGastoParameter);
        }
    
        public virtual int SP_InformePersonalAdmServicios(Nullable<System.Guid> idGroupInformePersona)
        {
            var idGroupInformePersonaParameter = idGroupInformePersona.HasValue ?
                new ObjectParameter("IdGroupInformePersona", idGroupInformePersona) :
                new ObjectParameter("IdGroupInformePersona", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformePersonalAdmServicios", idGroupInformePersonaParameter);
        }
    
        public virtual int SP_InformePersonalCementerio(Nullable<System.Guid> idGroupInformePersona)
        {
            var idGroupInformePersonaParameter = idGroupInformePersona.HasValue ?
                new ObjectParameter("IdGroupInformePersona", idGroupInformePersona) :
                new ObjectParameter("IdGroupInformePersona", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformePersonalCementerio", idGroupInformePersonaParameter);
        }
    
        public virtual int SP_InformePersonalEducacion(Nullable<System.Guid> idGroupInformePersona)
        {
            var idGroupInformePersonaParameter = idGroupInformePersona.HasValue ?
                new ObjectParameter("IdGroupInformePersona", idGroupInformePersona) :
                new ObjectParameter("IdGroupInformePersona", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformePersonalEducacion", idGroupInformePersonaParameter);
        }
    
        public virtual int SP_InformePersonalMunicipioTotal(Nullable<System.Guid> idGroupInformePersona)
        {
            var idGroupInformePersonaParameter = idGroupInformePersona.HasValue ?
                new ObjectParameter("IdGroupInformePersona", idGroupInformePersona) :
                new ObjectParameter("IdGroupInformePersona", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformePersonalMunicipioTotal", idGroupInformePersonaParameter);
        }
    
        public virtual int SP_InformePersonalSalud(Nullable<System.Guid> idGroupInformePersona)
        {
            var idGroupInformePersonaParameter = idGroupInformePersona.HasValue ?
                new ObjectParameter("IdGroupInformePersona", idGroupInformePersona) :
                new ObjectParameter("IdGroupInformePersona", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformePersonalSalud", idGroupInformePersonaParameter);
        }
    
        public virtual int SP_InformeProveedoresAdmServicios(Nullable<System.Guid> idGroupInformeProveedores)
        {
            var idGroupInformeProveedoresParameter = idGroupInformeProveedores.HasValue ?
                new ObjectParameter("IdGroupInformeProveedores", idGroupInformeProveedores) :
                new ObjectParameter("IdGroupInformeProveedores", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeProveedoresAdmServicios", idGroupInformeProveedoresParameter);
        }
    
        public virtual int SP_InformeProveedoresCementerio(Nullable<System.Guid> idGroupInformeProveedores)
        {
            var idGroupInformeProveedoresParameter = idGroupInformeProveedores.HasValue ?
                new ObjectParameter("IdGroupInformeProveedores", idGroupInformeProveedores) :
                new ObjectParameter("IdGroupInformeProveedores", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeProveedoresCementerio", idGroupInformeProveedoresParameter);
        }
    
        public virtual int SP_InformeProveedoresEducacion(Nullable<System.Guid> idGroupInformeProveedores)
        {
            var idGroupInformeProveedoresParameter = idGroupInformeProveedores.HasValue ?
                new ObjectParameter("IdGroupInformeProveedores", idGroupInformeProveedores) :
                new ObjectParameter("IdGroupInformeProveedores", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeProveedoresEducacion", idGroupInformeProveedoresParameter);
        }
    
        public virtual int SP_InformeProveedoresMunicipioTotal(Nullable<System.Guid> idGroupInformeProveedores)
        {
            var idGroupInformeProveedoresParameter = idGroupInformeProveedores.HasValue ?
                new ObjectParameter("IdGroupInformeProveedores", idGroupInformeProveedores) :
                new ObjectParameter("IdGroupInformeProveedores", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeProveedoresMunicipioTotal", idGroupInformeProveedoresParameter);
        }
    
        public virtual int SP_InformeSubsidio(Nullable<System.Guid> idGroupReportSubsidio)
        {
            var idGroupReportSubsidioParameter = idGroupReportSubsidio.HasValue ?
                new ObjectParameter("IdGroupReportSubsidio", idGroupReportSubsidio) :
                new ObjectParameter("IdGroupReportSubsidio", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeSubsidio", idGroupReportSubsidioParameter);
        }
    
        public virtual int SP_PersonalAdmServicios_RangoAntiguedad(Nullable<System.Guid> idGroupInformePersonal)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalAdmServicios_RangoAntiguedad", idGroupInformePersonalParameter);
        }
    
        public virtual int SP_PersonalCementerio_RangoAntiguedad(Nullable<System.Guid> idGroupInformePersonal)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalCementerio_RangoAntiguedad", idGroupInformePersonalParameter);
        }
    
        public virtual int SP_PersonalEducacion_RangoAntiguedad(Nullable<System.Guid> idGroupInformePersonal)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalEducacion_RangoAntiguedad", idGroupInformePersonalParameter);
        }
    
        public virtual int SP_PersonalMunicipioTotal_RangoAntiguedad(Nullable<System.Guid> idGroupInformePersonal)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalMunicipioTotal_RangoAntiguedad", idGroupInformePersonalParameter);
        }
    
        public virtual int SP_PersonalSalud_RangoAntiguedad(Nullable<System.Guid> idGroupInformePersonal)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalSalud_RangoAntiguedad", idGroupInformePersonalParameter);
        }
    
        public virtual int SP_InformeIngreso(Nullable<System.Guid> idGroupReportIngreso)
        {
            var idGroupReportIngresoParameter = idGroupReportIngreso.HasValue ?
                new ObjectParameter("IdGroupReportIngreso", idGroupReportIngreso) :
                new ObjectParameter("IdGroupReportIngreso", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeIngreso", idGroupReportIngresoParameter);
        }
    
        public virtual int SP_InformeCorporaciones(Nullable<System.Guid> idGroupInforme)
        {
            var idGroupInformeParameter = idGroupInforme.HasValue ?
                new ObjectParameter("IdGroupInforme", idGroupInforme) :
                new ObjectParameter("IdGroupInforme", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeCorporaciones", idGroupInformeParameter);
        }
    }
}
