//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GastoTransparenteMunicipalEntities : DbContext
    {
        public GastoTransparenteMunicipalEntities()
            : base("name=GastoTransparenteMunicipalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Corporacion_Ano> Corporacion_Ano { get; set; }
        public virtual DbSet<Corporacion_Nivel1> Corporacion_Nivel1 { get; set; }
        public virtual DbSet<Gasto_Ano> Gasto_Ano { get; set; }
        public virtual DbSet<Gasto_Nivel1> Gasto_Nivel1 { get; set; }
        public virtual DbSet<Gasto_Nivel2> Gasto_Nivel2 { get; set; }
        public virtual DbSet<Gasto_Nivel3> Gasto_Nivel3 { get; set; }
        public virtual DbSet<Gasto_Nivel4> Gasto_Nivel4 { get; set; }
        public virtual DbSet<GastoInforme> GastoInforme { get; set; }
        public virtual DbSet<Ingreso_Ano> Ingreso_Ano { get; set; }
        public virtual DbSet<Ingreso_Nivel1> Ingreso_Nivel1 { get; set; }
        public virtual DbSet<Ingreso_Nivel2> Ingreso_Nivel2 { get; set; }
        public virtual DbSet<Ingreso_Nivel3> Ingreso_Nivel3 { get; set; }
        public virtual DbSet<Ingreso_Nivel4> Ingreso_Nivel4 { get; set; }
        public virtual DbSet<IngresoInforme> IngresoInforme { get; set; }
        public virtual DbSet<Municipalidad> Municipalidad { get; set; }
        public virtual DbSet<Personal_Adm_Nivel1> Personal_Adm_Nivel1 { get; set; }
        public virtual DbSet<Personal_Adm_Nivel2> Personal_Adm_Nivel2 { get; set; }
        public virtual DbSet<Personal_Ano> Personal_Ano { get; set; }
        public virtual DbSet<Personal_Cementerio_Nivel1> Personal_Cementerio_Nivel1 { get; set; }
        public virtual DbSet<Personal_Cementerio_Nivel2> Personal_Cementerio_Nivel2 { get; set; }
        public virtual DbSet<Personal_Educacion_Nivel1> Personal_Educacion_Nivel1 { get; set; }
        public virtual DbSet<Personal_Educacion_Nivel2> Personal_Educacion_Nivel2 { get; set; }
        public virtual DbSet<Personal_EducacionInforme> Personal_EducacionInforme { get; set; }
        public virtual DbSet<Personal_Salud_Nivel1> Personal_Salud_Nivel1 { get; set; }
        public virtual DbSet<Personal_Salud_Nivel2> Personal_Salud_Nivel2 { get; set; }
        public virtual DbSet<Personal_Total_Nivel1> Personal_Total_Nivel1 { get; set; }
        public virtual DbSet<Personal_Total_Nivel2> Personal_Total_Nivel2 { get; set; }
        public virtual DbSet<Proveedor_Adm_Nivel1> Proveedor_Adm_Nivel1 { get; set; }
        public virtual DbSet<Proveedor_Adm_Nivel2> Proveedor_Adm_Nivel2 { get; set; }
        public virtual DbSet<Proveedor_Ano> Proveedor_Ano { get; set; }
        public virtual DbSet<Proveedor_Cementerio_Nivel1> Proveedor_Cementerio_Nivel1 { get; set; }
        public virtual DbSet<Proveedor_Cementerio_Nivel2> Proveedor_Cementerio_Nivel2 { get; set; }
        public virtual DbSet<Proveedor_Educacion_Nivel1> Proveedor_Educacion_Nivel1 { get; set; }
        public virtual DbSet<Proveedor_Educacion_Nivel2> Proveedor_Educacion_Nivel2 { get; set; }
        public virtual DbSet<Proveedor_Salud_Nivel1> Proveedor_Salud_Nivel1 { get; set; }
        public virtual DbSet<Proveedor_Salud_Nivel2> Proveedor_Salud_Nivel2 { get; set; }
        public virtual DbSet<Proveedor_Total_Nivel1> Proveedor_Total_Nivel1 { get; set; }
        public virtual DbSet<Proveedor_Total_Nivel2> Proveedor_Total_Nivel2 { get; set; }
        public virtual DbSet<Subsidio_Ano> Subsidio_Ano { get; set; }
        public virtual DbSet<Subsidio_Nivel1> Subsidio_Nivel1 { get; set; }
        public virtual DbSet<Subsidio_Nivel2> Subsidio_Nivel2 { get; set; }
        public virtual DbSet<Subsidio_Nivel3> Subsidio_Nivel3 { get; set; }
        public virtual DbSet<Personal_AdmInforme> Personal_AdmInforme { get; set; }
        public virtual DbSet<Personal_CementerioInforme> Personal_CementerioInforme { get; set; }
        public virtual DbSet<Personal_SaludInforme> Personal_SaludInforme { get; set; }
        public virtual DbSet<SubsidioInforme> SubsidioInforme { get; set; }
    
        public virtual int SP_InformeGasto(Nullable<System.Guid> idGroupReportGasto, Nullable<long> idAn)
        {
            var idGroupReportGastoParameter = idGroupReportGasto.HasValue ?
                new ObjectParameter("IdGroupReportGasto", idGroupReportGasto) :
                new ObjectParameter("IdGroupReportGasto", typeof(System.Guid));
    
            var idAnParameter = idAn.HasValue ?
                new ObjectParameter("IdAn", idAn) :
                new ObjectParameter("IdAn", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeGasto", idGroupReportGastoParameter, idAnParameter);
        }
    
        public virtual int SP_InformeIngreso(Nullable<System.Guid> idGroupReportIngreso, Nullable<long> idAn)
        {
            var idGroupReportIngresoParameter = idGroupReportIngreso.HasValue ?
                new ObjectParameter("IdGroupReportIngreso", idGroupReportIngreso) :
                new ObjectParameter("IdGroupReportIngreso", typeof(System.Guid));
    
            var idAnParameter = idAn.HasValue ?
                new ObjectParameter("IdAn", idAn) :
                new ObjectParameter("IdAn", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeIngreso", idGroupReportIngresoParameter, idAnParameter);
        }
    
        public virtual int SP_InformePersonalEducacion(Nullable<System.Guid> idGroupInformePersona, Nullable<long> idAn)
        {
            var idGroupInformePersonaParameter = idGroupInformePersona.HasValue ?
                new ObjectParameter("IdGroupInformePersona", idGroupInformePersona) :
                new ObjectParameter("IdGroupInformePersona", typeof(System.Guid));
    
            var idAnParameter = idAn.HasValue ?
                new ObjectParameter("IdAn", idAn) :
                new ObjectParameter("IdAn", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformePersonalEducacion", idGroupInformePersonaParameter, idAnParameter);
        }
    
        public virtual int SP_PersonalEducacion_RangoAntiguedad(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalEducacion_RangoAntiguedad", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_InformeGastoArea(Nullable<System.Guid> idGroupInformeGasto, Nullable<long> idAno)
        {
            var idGroupInformeGastoParameter = idGroupInformeGasto.HasValue ?
                new ObjectParameter("IdGroupInformeGasto", idGroupInformeGasto) :
                new ObjectParameter("IdGroupInformeGasto", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeGastoArea", idGroupInformeGastoParameter, idAnoParameter);
        }
    
        public virtual int SP_InformeGastoCuenta(Nullable<System.Guid> idGroupInformeGasto, Nullable<long> idAno)
        {
            var idGroupInformeGastoParameter = idGroupInformeGasto.HasValue ?
                new ObjectParameter("IdGroupInformeGasto", idGroupInformeGasto) :
                new ObjectParameter("IdGroupInformeGasto", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeGastoCuenta", idGroupInformeGastoParameter, idAnoParameter);
        }
    
        public virtual int SP_InformeIngresoArea(Nullable<System.Guid> idGroupInformeIngreso, Nullable<long> idAno)
        {
            var idGroupInformeIngresoParameter = idGroupInformeIngreso.HasValue ?
                new ObjectParameter("IdGroupInformeIngreso", idGroupInformeIngreso) :
                new ObjectParameter("IdGroupInformeIngreso", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeIngresoArea", idGroupInformeIngresoParameter, idAnoParameter);
        }
    
        public virtual int SP_InformeIngresoCuenta(Nullable<System.Guid> idGroupInformeIngreso, Nullable<long> idAno)
        {
            var idGroupInformeIngresoParameter = idGroupInformeIngreso.HasValue ?
                new ObjectParameter("IdGroupInformeIngreso", idGroupInformeIngreso) :
                new ObjectParameter("IdGroupInformeIngreso", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeIngresoCuenta", idGroupInformeIngresoParameter, idAnoParameter);
        }
    
        public virtual int SP_InformePersonalEducacionNivel1(Nullable<long> idAno)
        {
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformePersonalEducacionNivel1", idAnoParameter);
        }
    
        public virtual int SP_PersonalEducacion_CalidadJuridica(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalEducacion_CalidadJuridica", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalEducacion_Estamento(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalEducacion_Estamento", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalEducacion_Grado(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalEducacion_Grado", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalEducacion_NivelEducacion(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalEducacion_NivelEducacion", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalEducacion_Profesion(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalEducacion_Profesion", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalEducacion_RangoAntiguedad1(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalEducacion_RangoAntiguedad1", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalEducacion_RangoEtario(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalEducacion_RangoEtario", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_InformePersonalAdm(Nullable<System.Guid> idGroupInformePersona, Nullable<long> idAn)
        {
            var idGroupInformePersonaParameter = idGroupInformePersona.HasValue ?
                new ObjectParameter("IdGroupInformePersona", idGroupInformePersona) :
                new ObjectParameter("IdGroupInformePersona", typeof(System.Guid));
    
            var idAnParameter = idAn.HasValue ?
                new ObjectParameter("IdAn", idAn) :
                new ObjectParameter("IdAn", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformePersonalAdm", idGroupInformePersonaParameter, idAnParameter);
        }
    
        public virtual int SP_InformePersonalCementerio(Nullable<System.Guid> idGroupInformePersona, Nullable<long> idAn)
        {
            var idGroupInformePersonaParameter = idGroupInformePersona.HasValue ?
                new ObjectParameter("IdGroupInformePersona", idGroupInformePersona) :
                new ObjectParameter("IdGroupInformePersona", typeof(System.Guid));
    
            var idAnParameter = idAn.HasValue ?
                new ObjectParameter("IdAn", idAn) :
                new ObjectParameter("IdAn", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformePersonalCementerio", idGroupInformePersonaParameter, idAnParameter);
        }
    
        public virtual int SP_InformePersonalSalud(Nullable<System.Guid> idGroupInformePersona, Nullable<long> idAn)
        {
            var idGroupInformePersonaParameter = idGroupInformePersona.HasValue ?
                new ObjectParameter("IdGroupInformePersona", idGroupInformePersona) :
                new ObjectParameter("IdGroupInformePersona", typeof(System.Guid));
    
            var idAnParameter = idAn.HasValue ?
                new ObjectParameter("IdAn", idAn) :
                new ObjectParameter("IdAn", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformePersonalSalud", idGroupInformePersonaParameter, idAnParameter);
        }
    
        public virtual int SP_InformePersonalAdmNivel1(Nullable<long> idAno)
        {
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformePersonalAdmNivel1", idAnoParameter);
        }
    
        public virtual int SP_InformePersonalCementerioNivel1(Nullable<long> idAno)
        {
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformePersonalCementerioNivel1", idAnoParameter);
        }
    
        public virtual int SP_InformePersonalSaludNivel1(Nullable<long> idAno)
        {
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformePersonalSaludNivel1", idAnoParameter);
        }
    
        public virtual int SP_PersonalAdm_CalidadJuridica(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalAdm_CalidadJuridica", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalAdm_Estamento(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalAdm_Estamento", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalAdm_Grado(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalAdm_Grado", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalAdm_NivelAdm(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalAdm_NivelAdm", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalAdm_Profesion(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalAdm_Profesion", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalAdm_RangoAntiguedad(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalAdm_RangoAntiguedad", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalAdm_RangoEtario(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalAdm_RangoEtario", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalCementerio_CalidadJuridica(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalCementerio_CalidadJuridica", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalCementerio_Estamento(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalCementerio_Estamento", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalCementerio_Grado(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalCementerio_Grado", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalCementerio_NivelCementerio(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalCementerio_NivelCementerio", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalCementerio_Profesion(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalCementerio_Profesion", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalCementerio_RangoAntiguedad(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalCementerio_RangoAntiguedad", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalCementerio_RangoEtario(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalCementerio_RangoEtario", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalSalud_CalidadJuridica(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalSalud_CalidadJuridica", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalSalud_Estamento(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalSalud_Estamento", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalSalud_Grado(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalSalud_Grado", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalSalud_NivelSalud(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalSalud_NivelSalud", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalSalud_Profesion(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalSalud_Profesion", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalSalud_RangoAntiguedad(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalSalud_RangoAntiguedad", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalSalud_RangoEtario(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalSalud_RangoEtario", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_InformePersonalMunicipioTotal(Nullable<System.Guid> idGroupInformePersona, Nullable<long> idAn)
        {
            var idGroupInformePersonaParameter = idGroupInformePersona.HasValue ?
                new ObjectParameter("IdGroupInformePersona", idGroupInformePersona) :
                new ObjectParameter("IdGroupInformePersona", typeof(System.Guid));
    
            var idAnParameter = idAn.HasValue ?
                new ObjectParameter("IdAn", idAn) :
                new ObjectParameter("IdAn", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformePersonalMunicipioTotal", idGroupInformePersonaParameter, idAnParameter);
        }
    
        public virtual int SP_InformePersonalMunicipioTotalNivel1(Nullable<long> idAno)
        {
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformePersonalMunicipioTotalNivel1", idAnoParameter);
        }
    
        public virtual int SP_PersonalMunicipioTotal_CalidadJuridica(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalMunicipioTotal_CalidadJuridica", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalMunicipioTotal_Estamento(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalMunicipioTotal_Estamento", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalMunicipioTotal_Grado(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalMunicipioTotal_Grado", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalMunicipioTotal_NivelEducacion(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalMunicipioTotal_NivelEducacion", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalMunicipioTotal_Profesion(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalMunicipioTotal_Profesion", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalMunicipioTotal_RangoAntiguedad(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalMunicipioTotal_RangoAntiguedad", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_PersonalMunicipioTotal_RangoEtario(Nullable<System.Guid> idGroupInformePersonal, Nullable<long> idAno)
        {
            var idGroupInformePersonalParameter = idGroupInformePersonal.HasValue ?
                new ObjectParameter("IdGroupInformePersonal", idGroupInformePersonal) :
                new ObjectParameter("IdGroupInformePersonal", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PersonalMunicipioTotal_RangoEtario", idGroupInformePersonalParameter, idAnoParameter);
        }
    
        public virtual int SP_InformeSubsidio(Nullable<System.Guid> idGroupReportSubsidio, Nullable<long> idAn)
        {
            var idGroupReportSubsidioParameter = idGroupReportSubsidio.HasValue ?
                new ObjectParameter("IdGroupReportSubsidio", idGroupReportSubsidio) :
                new ObjectParameter("IdGroupReportSubsidio", typeof(System.Guid));
    
            var idAnParameter = idAn.HasValue ?
                new ObjectParameter("IdAn", idAn) :
                new ObjectParameter("IdAn", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeSubsidio", idGroupReportSubsidioParameter, idAnParameter);
        }
    
        public virtual int SP_InformeSubsidioNivel1(Nullable<System.Guid> idGroupInformeSubsidio, Nullable<long> idAno)
        {
            var idGroupInformeSubsidioParameter = idGroupInformeSubsidio.HasValue ?
                new ObjectParameter("IdGroupInformeSubsidio", idGroupInformeSubsidio) :
                new ObjectParameter("IdGroupInformeSubsidio", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeSubsidioNivel1", idGroupInformeSubsidioParameter, idAnoParameter);
        }
    
        public virtual int SP_InformeSubsidioNivel2(Nullable<System.Guid> idGroupInformeSubsidio, Nullable<long> idAno)
        {
            var idGroupInformeSubsidioParameter = idGroupInformeSubsidio.HasValue ?
                new ObjectParameter("IdGroupInformeSubsidio", idGroupInformeSubsidio) :
                new ObjectParameter("IdGroupInformeSubsidio", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeSubsidioNivel2", idGroupInformeSubsidioParameter, idAnoParameter);
        }
    
        public virtual int SP_InformeSubsidioNivel3(Nullable<System.Guid> idGroupInformeSubsidio, Nullable<long> idAno)
        {
            var idGroupInformeSubsidioParameter = idGroupInformeSubsidio.HasValue ?
                new ObjectParameter("IdGroupInformeSubsidio", idGroupInformeSubsidio) :
                new ObjectParameter("IdGroupInformeSubsidio", typeof(System.Guid));
    
            var idAnoParameter = idAno.HasValue ?
                new ObjectParameter("IdAno", idAno) :
                new ObjectParameter("IdAno", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InformeSubsidioNivel3", idGroupInformeSubsidioParameter, idAnoParameter);
        }
    }
}
