//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeGastoGeneral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InformeGastoGeneral()
        {
            this.InformeGastoNivel1 = new HashSet<InformeGastoNivel1>();
        }
    
        public long IdInformeGastoGeneral { get; set; }
        public Nullable<System.Guid> IdGroupInformeGasto { get; set; }
        public Nullable<int> IdMunicipalidad { get; set; }
        public Nullable<double> TotalMontoPresupuestadoAnual { get; set; }
        public Nullable<double> TotalMontoGastado { get; set; }
        public Nullable<int> AnoInforme { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Municipalidad Municipalidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformeGastoNivel1> InformeGastoNivel1 { get; set; }
    }
}
