//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeSubsidioOrganizacion
    {
        public Nullable<int> IdMunicipalidad { get; set; }
        public Nullable<System.Guid> IdGroupInformeSubsidio { get; set; }
        public string Categoria { get; set; }
        public string Organizacion { get; set; }
        public Nullable<double> TotalMonto { get; set; }
        public Nullable<int> AnoInforme { get; set; }
        public Nullable<int> MesInforme { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public long IdInformeSubsidioOrganizacion { get; set; }
    }
}
