//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformePersonalAdmServicios
    {
        public long IdInformePersonal { get; set; }
        public Nullable<System.Guid> IdGroupInformePersonal { get; set; }
        public Nullable<int> IdMunicipalidad { get; set; }
        public Nullable<int> AnoInforme { get; set; }
        public Nullable<int> MesInforme { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string GENERO { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string CALIDADJURIDICA { get; set; }
        public string PROFESION { get; set; }
        public string NIVELACADEMICO { get; set; }
        public string ESTAMENTO { get; set; }
        public Nullable<int> GRADO { get; set; }
        public string ANTIGUEDAD { get; set; }
        public string AREA { get; set; }
        public Nullable<long> SUELDOHABERES { get; set; }
    }
}
