//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformePersonalResultadoAdmServicios
    {
        public long IdInformePersonalResultado { get; set; }
        public Nullable<long> IdInformePersonalCategoria { get; set; }
        public string Nombre { get; set; }
        public string Genero { get; set; }
        public Nullable<long> SueldoPromedio { get; set; }
        public Nullable<int> CantidadFuncionarios { get; set; }
    
        public virtual InformePersonalCategoriaAdmServicios InformePersonalCategoriaAdmServicios { get; set; }
    }
}
