//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeGastoNivel2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InformeGastoNivel2()
        {
            this.InformeGastoNivel3 = new HashSet<InformeGastoNivel3>();
        }
    
        public System.Guid IdInformeGastoNivel2 { get; set; }
        public System.Guid IdInformeGastoNivel1 { get; set; }
        public string Nombre { get; set; }
        public string NombreGrupo { get; set; }
        public Nullable<double> TotalDePresupuestoNV2 { get; set; }
        public Nullable<double> TotalDeGastoNV2 { get; set; }
        public Nullable<double> PorcentajeDelTotalDePresupuesto { get; set; }
        public Nullable<double> PorcentajeDelTotalDeGasto { get; set; }
        public string Descripcion { get; set; }
    
        public virtual InformeGastoNivel1 InformeGastoNivel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformeGastoNivel3> InformeGastoNivel3 { get; set; }
    }
}
