//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeSubsidioOrganizacion
    {
        public Nullable<int> IdMunicipalidad { get; set; }
        public Nullable<System.Guid> IdGroupInformeSubsidio { get; set; }
        public string Categoria { get; set; }
        public string Organizacion { get; set; }
        public Nullable<double> TotalMonto { get; set; }
        public Nullable<int> AnoInforme { get; set; }
        public Nullable<int> MesInforme { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public long IdInformeSubsidioOrganizacion { get; set; }
    }
}
