//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeIngresoNivel1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InformeIngresoNivel1()
        {
            this.InformeIngresoNivel2 = new HashSet<InformeIngresoNivel2>();
        }
    
        public System.Guid IdInformeIngresoNivel1 { get; set; }
        public Nullable<int> IdMunicipalidad { get; set; }
        public long IdInformeIngresoGeneral { get; set; }
        public string Nombre { get; set; }
        public string NombreGrupo { get; set; }
        public Nullable<double> TotalDePresupuestoNV1 { get; set; }
        public Nullable<double> TotalDeIngresoNV1 { get; set; }
        public Nullable<double> PorcentajeDelTotalDePresupuesto { get; set; }
        public Nullable<double> PorcentajeDelTotalDeIngreso { get; set; }
        public string Descripcion { get; set; }
    
        public virtual InformeIngresoGeneral InformeIngresoGeneral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformeIngresoNivel2> InformeIngresoNivel2 { get; set; }
    }
}
