//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeIngresoGeneral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InformeIngresoGeneral()
        {
            this.InformeIngresoNivel1 = new HashSet<InformeIngresoNivel1>();
        }
    
        public long IdInformeIngresoGeneral { get; set; }
        public Nullable<System.Guid> IdGroupInformeIngreso { get; set; }
        public Nullable<int> IdMunicipalidad { get; set; }
        public Nullable<double> TotalMontoPresupuestadoAnual { get; set; }
        public Nullable<double> TotalMontoGastado { get; set; }
        public Nullable<int> AnoInforme { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Municipalidad Municipalidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformeIngresoNivel1> InformeIngresoNivel1 { get; set; }
    }
}
