//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeIngresoNivel3
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InformeIngresoNivel3()
        {
            this.InformeIngresoNivel4 = new HashSet<InformeIngresoNivel4>();
        }
    
        public System.Guid IdInformeIngresoNivel3 { get; set; }
        public System.Guid IdInformeIngresoNivel2 { get; set; }
        public string Nombre { get; set; }
        public string NombreGrupo { get; set; }
        public Nullable<double> TotalDePresupuestoNV3 { get; set; }
        public Nullable<double> TotalDeIngresoNV3 { get; set; }
        public Nullable<double> PorcentajeDelTotalDePresupuesto { get; set; }
        public Nullable<double> PorcentajeDelTotalDeIngreso { get; set; }
        public string Descripcion { get; set; }
    
        public virtual InformeIngresoNivel2 InformeIngresoNivel2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformeIngresoNivel4> InformeIngresoNivel4 { get; set; }
    }
}
