//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeGastoNivel4
    {
        public System.Guid IdInformeGastoNivel4 { get; set; }
        public System.Guid IdInformeGastoNivel3 { get; set; }
        public string Nombre { get; set; }
        public string NombreGrupo { get; set; }
        public Nullable<double> TotalDePresupuestoNV4 { get; set; }
        public Nullable<double> TotalDeGastoNV4 { get; set; }
        public Nullable<double> PorcentajeDelTotalDePresupuesto { get; set; }
        public Nullable<double> PorcentajeDelTotalDeGasto { get; set; }
        public string Descripcion { get; set; }
    
        public virtual InformeGastoNivel3 InformeGastoNivel3 { get; set; }
    }
}
