//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeIngresoNivel4
    {
        public System.Guid IdInformeIngresoNivel4 { get; set; }
        public System.Guid IdInformeIngresoNivel3 { get; set; }
        public string Nombre { get; set; }
        public string NombreGrupo { get; set; }
        public Nullable<double> TotalDePresupuestoNV4 { get; set; }
        public Nullable<double> TotalDeIngresoNV4 { get; set; }
        public Nullable<double> PorcentajeDelTotalDePresupuesto { get; set; }
        public Nullable<double> PorcentajeDelTotalDeIngreso { get; set; }
        public string Descripcion { get; set; }
    
        public virtual InformeIngresoNivel3 InformeIngresoNivel3 { get; set; }
    }
}
