//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeGasto
    {
        public long IdInformeGasto { get; set; }
        public string TIPO { get; set; }
        public string AREANIVEL1A { get; set; }
        public string AREANIVEL2 { get; set; }
        public string CUENTANIVEL1 { get; set; }
        public string CUENTANIVEL2 { get; set; }
        public Nullable<double> MontoPresupuestadoAnual { get; set; }
        public Nullable<double> MontoGastado { get; set; }
        public string Municipio { get; set; }
        public Nullable<int> IdMunicipalidad { get; set; }
        public Nullable<int> IdtipoGasto { get; set; }
        public Nullable<int> AnoInforme { get; set; }
        public Nullable<int> MesInforme { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> IdGroupInformeGasto { get; set; }
    
        public virtual Municipalidad Municipalidad { get; set; }
    }
}
