//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_Salud_Nivel2
    {
        public long IdNivel2 { get; set; }
        public Nullable<long> IdNivel1 { get; set; }
        public string Nombre { get; set; }
        public Nullable<long> MontoMujer { get; set; }
        public Nullable<long> MontoHombre { get; set; }
        public Nullable<long> CantidadMujer { get; set; }
        public Nullable<long> CantidadHombre { get; set; }
    
        public virtual Personal_Salud_Nivel1 Personal_Salud_Nivel1 { get; set; }
    }
}
