//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_AdmInforme
    {
        public long IdInformePersonal { get; set; }
        public Nullable<System.Guid> IdGroupInformePersonal { get; set; }
        public string GENERO { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string CALIDADJURIDICA { get; set; }
        public string PROFESION { get; set; }
        public string NIVELACADEMICO { get; set; }
        public string ESTAMENTO { get; set; }
        public Nullable<int> GRADO { get; set; }
        public string ANTIGUEDAD { get; set; }
        public string AREA { get; set; }
        public Nullable<long> SUELDOHABERES { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
