//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor_CementerioInforme
    {
        public long IdInformeProveedores { get; set; }
        public Nullable<System.Guid> IdGroupInformeProveedores { get; set; }
        public Nullable<long> NumeroOrdenCompra { get; set; }
        public string Glosa { get; set; }
        public string Proveedor { get; set; }
        public string RUT { get; set; }
        public Nullable<long> Monto { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
