//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subsidio_Nivel3
    {
        public long IdNivel3 { get; set; }
        public Nullable<long> IdNivel2 { get; set; }
        public string Nombre { get; set; }
        public Nullable<long> Monto { get; set; }
    }
}
